---
collections:
  - name: community.general
    version: 5.8.7
  - name: community.sops
    version: 1.6.1
  - name: ansible.posix
    version: 1.5.2
  - name: ansible.utils
    version: 2.9.0
roles:
  - src: xanmanning.k3s
    version: v3.3.1
