---
collections:
  - name: community.general
    version: 5.8.4
  - name: community.sops
    version: 1.6.0
  - name: ansible.posix
    version: 1.5.1
  - name: ansible.utils
    version: 2.8.0
roles:
  - src: xanmanning.k3s
    version: v3.3.1
