apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik.yaml
  - bitnami.yaml
  - emberstack.yaml
  - external-dns.yaml
  - hajimari.yaml
  - grafana-charts.yaml
  - longhorn.yaml
  - jetstack.yaml
  - k8s-at-home.yaml
  - k8s-gateway.yaml
  - k8tz.yaml
  - metallb.yaml
  - metrics-server.yaml
  - prometheus-community.yaml
  - portainer.yaml
  - stakater.yaml
  - traefik.yaml
  - weaveworks-kured.yaml
