---
fail_fast: false
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - args:
          - --config-file
          - .github/linters/.yamllint.yaml
        id: yamllint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/sirosen/texthooks
    rev: 0.3.1
    hooks:
      - id: fix-smartquotes
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.10.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets
        exclude: tmpl/.*
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.17.1
    hooks:
      - id: check-renovate
        additional_dependencies: ['pyjson5']
  - repo: https://github.com/tarioch/flux-check-hook
    rev: v0.2.0
    hooks:
      - id: check-flux-helm-values
