---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1s9mnf5d22h6cqgljqcaaxgpzza49tg4a4uv58naelwy690zvus4s4yj5d3
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1s9mnf5d22h6cqgljqcaaxgpzza49tg4a4uv58naelwy690zvus4s4yj5d3
