---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  # TODO: Find a fix that allows cluster bootstrapping.
  # Comment out if metallb CRDs are not installed.
  - resources.yaml
