---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  creationTimestamp: null
  name: my-ip-space
  namespace: metallb-system
spec:
  addresses:
    - "$METALLB_LB_RANGE}"
  dependsOn:
    - name: metallb
      namespace: metallb-system
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  creationTimestamp: null
  name: l2advertisement1
  namespace: metallb-system
spec:
  ipAddressPools:
    - my-ip-space
  dependsOn:
    - name: metallb
      namespace: metallb-system
status: {}
---
