---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8tz
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: k8tz
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: k8tz
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    timezone: "${TIMEZONE}"
