---
kubernetes:
  children:
    master:
      hosts:
        k8s-1:
          ansible_host: 192.168.2.11
        k8s-2:
          ansible_host: 192.168.2.12
        k8s-3:
          ansible_host: 192.168.2.13
