---
kubernetes:
  children:
    master:
      hosts:
        k3s02.dev.lan:
          ansible_host: 192.168.2.12
        k3s03.dev.lan:
          ansible_host: 192.168.2.13
        k3s01.dev.lan:
          ansible_host: 192.168.2.11
    worker:
      hosts:
        k3s04.dev.lan:  # Raspberry PI
          ansible_host: 192.168.2.14
