---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Los_Angeles
  METALLB_LB_RANGE: 192.168.2.220-192.168.2.230
  METALLB_K8S_GATEWAY_ADDR: 192.168.2.220
  METALLB_TRAEFIK_ADDR: 192.168.2.221
