# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Sq5TsFheiZF6,iv:J+cfoROZ/sXUMohJ4O24JSSKHH50uolxXJKS5ZVSkTc=,tag:BRL/kGyDnJj95TmSqSVZkw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cMcxazYVyjZTFhfS9U8ckG+KuMTm,iv:Rclj0OnqWB5XhfUwwCScX8/xafnrGMIxzWRo+kAPf58=,tag:EdyFAwXwONpeliRtj2EnbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s9mnf5d22h6cqgljqcaaxgpzza49tg4a4uv58naelwy690zvus4s4yj5d3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVm1wMW14RDVZYWM5Ujdj
            NFRKZGxxYXBEaWkzTWlYMmR0VS91R2ZkRERzCnlFM1ZTQlp1bTk3YXBpU2FHN3Iv
            T3pmVURNTlY3UksrUTZQUVhrWDQvQjAKLS0tIEZ0Z2kvMmJ2KytwcjJ0dEs1VXRB
            Qi8vRzNpaU5DMVkwK3lxdFNlelFtUU0Kw1alEL+CA8wqVPE1w8WSwUdXsPaIPN+h
            hnPm0sTH25EBgfnMoP7vyGDx/xfAiQVPRPz1wHnkPjbEChZt/4QSlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T16:39:52Z"
    mac: ENC[AES256_GCM,data:L75N1vhiGajAZBr6ptyYfErKjmLCVsF1OPsHijgwFFXngsbIDAcsHvyy+pi6HZ9BQHS9sVUv0e58H2O8U4sHMl4Or+bdAinmZR8SGPuEpRVzGDg84K5ZxiKlJuquKvBT4nqNy2sxQPXi2vHD5lORPBqsTR8JtIIKJN5tgau5MBw=,iv:fG8lsjdoOc6ghDQySnoa9CSbC03SgpCIXelRbA2KJmA=,tag:s62jXjiQwweVJSCUCxn1sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
