kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto-config
stringData:
    mqtt.conf: ENC[AES256_GCM,data:4TNHenCLOBCUglE2FH8WZP4kIXnbKddHvvzJeYgiyuW0evgpKjHCA05vJnH4XOq0yGn7Yyymn8IDFBQuJrgXl/0t2bVOyp4=,iv:aKOBbG9KTjrZ2W3oeFI2E0OKOkCat537dPA6nbmVNoc=,tag:E4tC/BmDFYSSDY+P617XbQ==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:8O3Si2wu+Cxdvrtmgp0JpyHe3OtD+WHfqOt2NHnGhPb8LvfyArYxzQvcOABYUCRT3xZsckP8xYbVmMovcU9AEpR2caU7MTuPQcpqKA2pkoMb38MqGrsqAeZy8ZSpJ6zAEzm3uc6FLLGeRESk3jqkXJsC9vhdakY5kqt/5pyxD3yJ70IufP373Jd8XmScRx15CKN9gvSDBLFbp5l88ophp7Hxke2LlvWUQ9Kq/cU1Q3uzZM3LEtSugdIOG89JkjmqZm2yJ69hM14Uw2L8dyw+fdKFni6Q9hwcBHaPvfJHOBidsfOC+l0y/jT0zOEM,iv:6ygvsGndR5/ekaUdsKSlTZxPodBTA3kX9GqHJlg46+8=,tag:Jfp/ER1xmlpXNsGFy8ExWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s9mnf5d22h6cqgljqcaaxgpzza49tg4a4uv58naelwy690zvus4s4yj5d3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVmh3cDN1RjE5TllvNFRV
            ZHhiZGpwU3NUSWFQV3Y4MzBQY3ozOGEwb2hzCkE3ai9Takh4bGFrT3RvSEZ1anlh
            b0llS1NsY2VneThta2RoNGRxNmRFT2MKLS0tIFRFY094czk1R3M4THlCUENRcThK
            WDB2cmVheWsrbmxhaXM0MzBETFUzcXcKCkgNd57FIi6RBDImmyiVjEr/Y887Kgls
            P5ulICeyFZnv//PgkcDR8AosW0Dp8grb4YFkDKMQ7nGBV89DuZqvLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-21T01:02:55Z"
    mac: ENC[AES256_GCM,data:YdR7Qvno5zHHR2hSxKCEMTRCFD9MP3SGIWNh8AHFdBFAvoENqn7gLtflMhtYnzQwo7ldIhy+AxLGcgrE2neKWhvZYXNTXqYtdXkgTJdQvKSBfZ/wAsuPpkUpeItZnOSlM6f1S+Fx7zJo2DJ4sWyhMsZi1Tk1L/DDJSskLVBKLy0=,iv:iJzgSXWDeyqscjvdBGt8Qtm2lGNaeefgOxBADrrVO9k=,tag:t0WJp09MZaLv8Ul1mptOxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
