---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
spec:
  interval: 5m
  chart:
    spec:
      chart: mosquitto
      version: 4.8.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  values:
    podAnnotations:
      # This is the one in config.sops.yaml.
      secret.reloader.stakater.com/reload: "mosquitto-config"
      # The chart creates this configmap.
      configmap.reloader.stakater.com/reload: "mosquitto-config"
    image:
      repository: eclipse-mosquitto
      tag: 2.0.15
    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations: {}
        spec:
          externalTrafficPolicy: Local
    auth:
      enabled: true
    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-data
      configinc:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            secretName: mosquitto-config
