---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: mosquitto
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.15
    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: |-
            ${METALLB_MOSQUITTO_ADDR}
        spec:
          externalTrafficPolicy: Local
    auth:
      enabled: true
    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-data
      configinc:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            secretName: mosquitto-config
