---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: "./charts/metallb/charts/crds"
      version: '0.0.0'
      sourceRef:
        kind: GitRepository
        name: metallb-crd-source
        namespace: flux-system
      interval: 1hr
