---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: metallb-crd-source
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/metallb/metallb
  ref:
    # renovate: datasource=github-releases depName=metallb/metallb
    tag: "v0.13.4"
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
