# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-cloud-credentials
  namespace: networking
stringData:
    email: ${BOOTSTRAP_CLOUDFLARE_EMAIL}
    api-token: ${BOOTSTRAP_CLOUDFLARE_API_TOKEN}
