# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Kal1ZxBFwigmSfhkBZ7z3POHoe5s6BZBLYRBuc4+sAX6fcml7OQbKQ==,iv:GRgxPseiJfLD9EQ1iyxX5RIDB5JN2Ur6AhqXkWL7YTA=,tag:sQxPrfwjHQH7lUgDFTSzxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s9mnf5d22h6cqgljqcaaxgpzza49tg4a4uv58naelwy690zvus4s4yj5d3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRWtBUHR5Z0l1SmErRlV2
            enJPTi9mNW96dmdTL09YN2JhOVNJeE5jM2t3CmN6WW5GNTFOZ0FqQndiNm5iVDc5
            QU9Da3kzYTVKTVFYT1BITTNVQUVPQzQKLS0tIEdIZ0Qrb0pxbHV0bkRJcW51UThy
            OHFOcnNWN3VlaldnaDlVLzkrNFpFOWcKwNywD9kVRgpw7sFRlNd0/vW676Z26XPi
            9px42FKcl91N4iG1b2Z+ojZAvTTeR4YKmkNTri7qLNlGywE8IqzfGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-21T07:36:26Z"
    mac: ENC[AES256_GCM,data:bZFw71DsNHpQyJQ1s4qjCAFJKtWgg4JSVc7NWyLOc/92p7kLLoBT2KqeG0xTdeRzRwFW9aprPzzKZLECiCVa2wQvcfQ/3rSxirG66bJuZ4RNQMjek0UzS/I4Yn4y1XllZf2oEyp4NBnVJ6qt06qG6VilTdSsZCdwRm9mBAIR2Ks=,iv:j8iacdFJZJWw4Ic3nkH3UZ2xJMhywRi+hzrZeNAvUDo=,tag:r+vNSqTLjb3+mMWMRFkSdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
