# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:WpE8IR9P7sXIuGcLKjPJgfUeQpyfmHfq+spCwPBc9oIHl+rXf0m7yA==,iv:r8yBuZMeFHZierstav/UxtKZCkaTyZdil0X8ZeWzf2I=,tag:5fKjN95y6tL8jOjGGYjHOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s9mnf5d22h6cqgljqcaaxgpzza49tg4a4uv58naelwy690zvus4s4yj5d3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSGZlaU5SY1ZGS3JybHdl
            NzhJZ2hKTFJ2SzdkSnhIV0lxK0ROT3pUalFVCnVCT1ErNndINFV3eit3aGg2M2Zu
            QUpVTW9QcEZEYzcvWEk3S1NGM2pLTlkKLS0tIGJ5aTZwY2RoYWczYTUrUjhESWp0
            WVlsWWE4NS83TU5FdjRPd2U5NGw3RHcKQ9HcT5DaadxGHi20VZK7IQFVQWUOz+XP
            24dBmInA0pXGiIYkWGRlnWGWiKTPOWLn9fbIMlaCM1OvJHlujpDdvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T16:39:52Z"
    mac: ENC[AES256_GCM,data:02kjw0+uDiZiXJkT05dqQAHy4A3k7fOqg0KT4vAft7D/qEbEUa2m/3OkxCH/bhEpo9OuuK8HoW+MRpaV290IlF36Lsy7h12s6DJLpWVuxb6ytbD2qfp7Lc3wwHey616S6sbHYLG9wJPEBjBIKWxfFKzxrUZoMnhXez8XNbK+4O4=,iv:fUXmgAmw1GQw3VIVfDrxQ0EMrfZirJ3OwY9bZoNPuPU=,tag:n3tvOdjc4xOPA7U5CO/MmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
