---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: telegram
  namespace: flux-system
spec:
  type: telegra
  channel: !!str ${SECRET_TELEGRAM_CHANNEL}
  secretRef:
    name: telegram-bot-token
