# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: telegram-bot-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:bnzPDF/bG9iliPmb1XJI1DJhZ9JkXApfGL8ggUUkPzEYsQwyAifbuUE324evIA==,iv:kHqtAML4x4NHHWy7sKcrLufnXr7v9zNKpg+y3K4jUOc=,tag:3uwepkvSc3cQH0BkSenYIg==,type:str]
    address: ENC[AES256_GCM,data:UDBbtvQcoJ2XEG468VhWRZJsDsY2S2cE,iv:LNpyglB09gQ6G2LVMJOCr7+AravXl2C8zTG7Y6ey62c=,tag:4gc5rK1w1TxVDQ56cLygNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s9mnf5d22h6cqgljqcaaxgpzza49tg4a4uv58naelwy690zvus4s4yj5d3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByc3h0aXlQWDh1cVc4SWsy
            RGRHcmlwNXRYVGZzUnV3bmVLT2RLZFRIUlhBClJ3Q0FyRGIxUGlzbjYxL3pwYXhR
            bHdaNTJoMGJzdjBCQld6L20xK1F6MEEKLS0tIHYwdXJ5TkZhdjJJNUZVSUgxTnJq
            UHc0Q1VkZjRRM1dmNTVsMjFFVVQxUE0KGNM0T9ZV3LwaAaH8QZrdDoyNCltWTFIS
            O1sQzxlAC5nS5bBbxzhImNgTeV2wGOIFQHK7p/leUte5ZP4+l00WGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-20T21:33:00Z"
    mac: ENC[AES256_GCM,data:4YRX3IxkxJlTSJD65iKvQNIvlJXn12OzoUZuec9rQFaO9lFXUPebXDK1PCYd/dpOba2hB1u8kf7U8QGvYxZrnWybAURmDsiP2Rx/urltDBwEY/HuhLvGhESQor8C+EYTxT1lnzrFLj8ZhU6L7iCc+HhtHSA+P+os2Rsz5IC24Dk=,iv:BrwyH4yY0IelwuqhnAVebcDeQmymfVLXAl19KlvSTPk=,tag:nkwSmkdWXDIMzJPh1OHa9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
