# This is a basic workflow to help you get started with Actions

name: Pre-commit

# Controls when the workflow will run
on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run-precommit"
  run-precommit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: pre-commit
        # You may pin to the exact commit or the version.
        # uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507
        uses: pre-commit/action@v3.0.0
        # with:
        # options to pass to pre-commit run
        # extra_args: # optional, default is --all-files
