name: Check Renovate config

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: renovate-config-validator
        uses: rinchsan/renovate-config-validator@v0.0.11
        with:
          pattern: 'renovate.json5'
