---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hajimari-config-pv
  namespace: default
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    # TODO: Move to a permanent volume. We're just testing for now.
    volumeHandle: test-vol
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: hajimari-config-pv
  resources:
    requests:
      storage: 128Mi
