---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: portainer
      version: 1.0.38
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        hajimari.io/enable: "true"
        hajimari.io/icon: "video-input-antenna"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
      labels:
      hosts:
        - host: &host "portainer.${SECRET_DOMAIN}"
          paths:
            - path: "/"
      tls:
        - secretName: "portainer-tls"
          hosts:
            - *host
    persistence:
      enabled: true
      existingClaim: portainer-pvc
